### ISSUE TITLE
no sidecar appears

### ISSUE THREAD

**Issue by doutriaux1** [jupyter-widgets/jupyterlab-sidecar#13]
I installed jupyterlab via conda
followed instructions in README 
no matter what I do no sidecar appear, dissplay renders right bellow the cell
Any idea what is going on?

**Comment by doutriaux1** [comment]
you actually need to install the manager:
```bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by doutriaux1** [comment]
It  should be added to the README

**Comment by trbedwards** [comment]
I have this problem in jupyterlab 3.2.9. Upon running `jupyter labextension list` I see that jupyterlab-manager v3.0.1 and jupyterlab-sidecar v0.6.1 are installed.

**Comment by trbedwards** [comment]
Nevermind, it works now, perhaps I just needed to restart my jupyterlab server!
