### ISSUE TITLE
jupyterlab-sidecar compatibility with jupyter 1.0

### ISSUE THREAD

**Issue by downiec** [jupyter-widgets/jupyterlab-sidecar#18]
It seems that the sidecar extension is going to be broken once JupyterLab 1.0 is released. I noticed the sidecar extension (which my extension uses) is no longer working after I updated my extension for jupyterlab 1.0 release.

**Comment by SylvainCorlay** [comment]
Absolutely, although there is no backward compatibility guarantees between the alphas wither from semver semantica or in the actual releases of jupyterlab.

There has been way to many releases of 1.0.0-alpha (and for too long). We will update extensions after the 1.0 release.

**Comment by downiec** [comment]
Sounds good! I thought you might be waiting for the 1.0 release but just thought I'd mention it. Thanks!

**Comment by doutriaux1** [comment]
1.0 is out now. Any idea of when sidecar will be updated.
