### ISSUE TITLE
v0.4.0 o PyPi

### ISSUE THREAD

**Issue by js3711** [jupyter-widgets/jupyterlab-sidecar#28]
It does not appears as though sidecar 0.4.0 is available via Pypi . https://pypi.org/project/sidecar/#history.  Is this an automated process and is this expected to occur soon?

**Comment by SylvainCorlay** [comment]
Hello, @js3711,

The Python package version is 0.3.0, and the npm package version is 0.4.0 (for the jupyterlab javascript extension).
At the moment we don't bundle the latter with the former.

**Comment by js3711** [comment]
Ah, thanks for the response!  Appreciate your work on this!

I was confused by the github tag# vs the pypi version number
