### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by IrtazaS** [jupyter-widgets/jupyterlab-sidecar#3]
Error occurs after installing and importing sidecar:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-0d48f4bace40> in <module>()
----> 1 from sidecar import Sidecar
      2 from ipywidgets import IntSlider

ModuleNotFoundError: No module named 'sidecar'

**Comment by SylvainCorlay** [comment]
You probably did not install sidecar in the right environment.

**Comment by IrtazaS** [comment]
It is shown as installed and enabled in my current environment:
`(jupyterlab-sandbox) jendeimac01:workspace irtazasyed$ jupyter labextension list
JupyterLab v0.32.1
Known labextensions:
   app dir: /anaconda3/envs/jupyterlab-sandbox/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.35.0  enabled  OK
@jupyter-widgets/jupyterlab-sidecar
        @jupyter-widgets/jupyterlab-sidecar v0.1.0  enabled  OK
jupyterlab_bokeh
        jupyterlab_bokeh v0.5.0  enabled  OK
`

**Comment by SylvainCorlay** [comment]
Yes, but there are two things at play:

 - the environment of the jupyter server, where the extension is to be installed.
 - the environment of the kernel, where the sidecar python package should be installed.

**Comment by IrtazaS** [comment]
I installed it in the kernel environment and it is working now. Thank you very much @SylvainCorlay !
