### ISSUE TITLE
Will jupyterlab-sidecar be further maintained and ported to Jupyterlab 2.x?

### ISSUE THREAD

**Issue by bernhard-42** [jupyter-widgets/jupyterlab-sidecar#41]
Currently the prerequisites in `package.json` are 

```json
"@jupyter-widgets/jupyterlab-manager": "^1.0.0",
"@jupyterlab/application": "^1.0.0"
```

which from my understanding are not compatible with Jupyterlab 2.x
And there might be other changes necessary ...

**Comment by SylvainCorlay** [comment]
Hey @bernhard-42 yes absolutely. This has just been a question of bandwidth as we maintain many extensions.
If you feel like opensing a PR to port it to 2.0, that would be awesome!

**Comment by kylebarron** [comment]
Do you have an idea of what would need to be updated for this to work in JupyterLab >=2?

**Comment by kylebarron** [comment]
Also, see the open PR: #38

**Comment by bernhard-42** [comment]
@kylebarron Yeah, I also try to come up with a pull request. Took me quite some time to get the karma tests running (I have no idea of karma and little experience with typescript). 
But now it works and I can see whether I can port Sidecar to JL 2.0

No promises ;-)

**Comment by kylebarron** [comment]
No, I'm saying there's already a Pull Request open, so you most likely don't need to spend more time on your own branch.

**Comment by bernhard-42** [comment]
I know, I copied some of the stuff from this PR, but didn't understand every change, so I started from scratch to see what the changes meant - a little bit of a learning experience ...

**Comment by psychemedia** [comment]
Is this issue closed by https://github.com/jupyter-widgets/jupyterlab-sidecar/pull/38 ?

**Comment by kylebarron** [comment]
Presumably, though I haven't tested it.
