### ISSUE TITLE
Sidecar side panel no longer appearing

### ISSUE THREAD

**Issue by psychemedia** [jupyter-widgets/jupyterlab-sidecar#94]
Noting that installing the sidecar package from PyPi into a recent environment launched via MyBinder, the sidecar no longer appears to work?

<img width="468" alt="image" src="https://user-images.githubusercontent.com/82988/180857185-533cb824-1413-4831-b6eb-6d82116d497a.png">

**Comment by eteq** [comment]
I would guess this is because of the changes in ipywidgets 8.0.x, which I think broke sidecar. #86 I think is hoping to fix this.

**Comment by jasongrout** [comment]
We just released sidecar 0.5.2 on pypi which should fix this.
